{
 "title": "Erweitert",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Stromfluss",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grid",
     "select": [
      [
       { "params": [ "AcPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Erzeugung",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "AcPvOnGridL1Power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Piko und Sma auf L1" ], "type": "alias" }
      ],
      [
       { "params": [ "AcPvOnGridL2Power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Piko auf L2" ], "type": "alias" }
      ],
      [
       { "params": [ "AcPvOnGridL3Power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Piko auf L3" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    }
   ]
  },
  {
   "title": "Solare Energie",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "GesamtEnergie Piko",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcEnergyForwardTotal" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "PIKO" }
     ]
    },
    {
     "alias": "GesamtEnergie Sma",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcEnergyForwardTotal" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "SMA" }
     ]
    },
    {
     "alias": "GesamtEnergie",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       {
        "params": [
         "PvInvertersAcEnergyForwardTotal"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "TagesEnergie",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "PvInvertersAcEnergyForwardDay" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    }
   ]
  },
  {
   "title": "Verbrauch aktuell von",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "Solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "AcConsumptionFromPv" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Batterie",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "AcConsumptionFromBatt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Netz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "AcConsumptionFromGrid" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    }
   ]
  },
  {
   "title": "Solarertrag aktuell nach",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "Direkt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "PvPowerToLoad" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Netz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "PvPowerToGrid" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Batterie",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "PvPowerToBattery" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "Dc0Current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "MultiPlus-II" }
     ]
    }
   ]
  },
  {
   "title": "Netzleistung",
   "type": "briangann-gauge-panel",
   "description": "negative Werte: -> zum Netz | positive Werte: <- vom Netz",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 5 },
   "format": "watt",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "grid",
     "select": [
      [
       { "params": [ "AcPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Meter" }
     ]
    }
   ]
  },
  {
   "title": "Batterie Leistung",
   "type": "briangann-gauge-panel",
   "description": "negative Werte: -> entladen | positive Werte: <- laden",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 5 },
   "format": "watt",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "DcBatteryPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    }
   ]
  },
  {
   "title": "Batterie SoC",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 5 },
   "format": "percent",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "Soc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "MultiPlus-II" }
     ]
    }
   ]
  },
  {
   "title": "Ac Lasten",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 5 },
   "format": "watt",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "AcConsumptionOnInputPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    }
   ]
  },
  {
   "title": "Pv Leistung",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 5 },
   "format": "watt",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "AcPvOnGridPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    }
   ]
  },
  {
   "title": "Alarme",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "AlarmsHighTemperature" ], "type": "field" },
       { "params": [ "Übertemperatur" ], "type": "alias" }
      ],
      [
       { "params": [ "AlarmsLowBattery" ], "type": "field" },
       { "params": [ "leere Batterie" ], "type": "alias" }
      ],
      [
       { "params": [ "AlarmsOverload" ], "type": "field" },
       { "params": [ "Überlast" ], "type": "alias" }
      ],
      [
       { "params": [ "AlarmsTemperatureSensor" ], "type": "field" },
       { "params": [ "Temperatur Sensor" ], "type": "alias" }
      ],
      [
       { "params": [ "AlarmsVoltageSensor" ], "type": "field" },
       { "params": [ "Spannungs Sensor" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "MultiPlus-II" }
     ]
    }
   ]
  },
  {
   "title": "LED Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "LedsAbsorption" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Konstantspannung" ], "type": "alias" }
      ],
      [
       { "params": [ "LedsBulk" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Konstantstrom" ], "type": "alias" }
      ],
      [
       { "params": [ "LedsFloat" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Ladeerhaltung" ], "type": "alias" }
      ],
      [
       { "params": [ "LedsLowBattery" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "niedrige Batteriespannung" ], "type": "alias" }
      ],
      [
       { "params": [ "LedsOverload" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Überlast" ], "type": "alias" }
      ],
      [
       { "params": [ "LedsTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Temperatur" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "MultiPlus-II" }
     ]
    }
   ]
  },
  {
   "title": "Pv Leistung",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "PIKO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcPower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "PIKO" }
     ]
    },
    {
     "alias": "SMA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcPower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "SMA" }
     ]
    },
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "AcPvOnGridPower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    { "target": "sun_altitude" }
   ]
  },
  {
   "title": "Aktuelle Pv Leistung",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "PIKO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "PIKO" }
     ]
    },
    {
     "alias": "SMA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "SMA" }
     ]
    }
   ]
  },
  {
   "title": "Raspi Cpu Temperatur",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Raspi",
     "select": [
      [
       { "params": [ "Temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "CpuInfo" }
     ]
    }
   ]
  },
  {
   "title": "Boot Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Raspi",
     "select": [
      [
       { "params": [ "BootTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Boot Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "CpuInfo" }
     ]
    }
   ]
  },
  {
   "title": "Cpu Last %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Raspi",
     "select": [
      [
       { "params": [ "Usage" ], "type": "field" },
       { "params": [ "Alle" ], "type": "alias" }
      ],
      [
       { "params": [ "UsageCore0" ], "type": "field" },
       { "params": [ "Core 0" ], "type": "alias" }
      ],
      [
       { "params": [ "UsageCore1" ], "type": "field" },
       { "params": [ "Core 1" ], "type": "alias" }
      ],
      [
       { "params": [ "UsageCore2" ], "type": "field" },
       { "params": [ "Core 2" ], "type": "alias" }
      ],
      [
       { "params": [ "UsageCore3" ], "type": "field" },
       { "params": [ "Core 3" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "CpuInfo" }
     ]
    }
   ]
  },
  {
   "title": "Batterie Leistung",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 16 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Gateway Dc",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "DcBatteryPower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "MultiPlus Dc",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "Dc0Power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "MultiPlus-II" }
     ]
    },
    {
     "alias": "MultiPlus Ac",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "AcActiveInL1P" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "MultiPlus-II" }
     ]
    }
   ]
  },
  {
   "title": "Netzleistung",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "grid",
     "select": [
      [
       { "params": [ "AcL1Power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Meter" }
     ]
    },
    {
     "alias": "L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "grid",
     "select": [
      [
       { "params": [ "AcL2Power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Meter" }
     ]
    },
    {
     "alias": "L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "grid",
     "select": [
      [
       { "params": [ "AcL3Power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Meter" }
     ]
    },
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "grid",
     "select": [
      [
       { "params": [ "AcPower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Meter" }
     ]
    }
   ]
  },
  {
   "title": "RAM in GB",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Raspi",
     "query": "SELECT mean(\"Total\") FROM \"Raspi\" WHERE (\"instance\" = '/dev/root') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1048576" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Memory" }
     ]
    },
    {
     "alias": "belegt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Raspi",
     "query": "SELECT mean(\"Total\") FROM \"Raspi\" WHERE (\"instance\" = '/dev/root') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1048576" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Memory" }
     ]
    },
    {
     "alias": "verfügbar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Raspi",
     "query": "SELECT mean(\"Total\") FROM \"Raspi\" WHERE (\"instance\" = '/dev/root') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Available" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1048576" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Memory" }
     ]
    }
   ]
  },
  {
   "title": "Batterie Spannung und Strom",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 24 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "MultiPlus-Spannung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "Dc0Voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "MultiPlus-II" }
     ]
    },
    {
     "alias": "MultiPlus-Strom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "Dc0Current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "MultiPlus-II" }
     ]
    }
   ]
  },
  {
   "title": "SSD in GB",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Raspi",
     "query": "SELECT mean(\"Total\") FROM \"Raspi\" WHERE (\"instance\" = '/dev/root') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1048576" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "/dev/root" }
     ]
    },
    {
     "alias": "belegt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Raspi",
     "query": "SELECT mean(\"Total\") FROM \"Raspi\" WHERE (\"instance\" = '/dev/root') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1048576" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "/dev/root" }
     ]
    },
    {
     "alias": "frei",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Raspi",
     "query": "SELECT mean(\"Total\") FROM \"Raspi\" WHERE (\"instance\" = '/dev/root') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1048576" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "/dev/root" }
     ]
    }
   ]
  },
  {
   "title": "Ac Lasten",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "AcConsumptionOnInputL1Power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "AcConsumptionOnInputL2Power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "AcConsumptionOnInputL3Power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "AcConsumptionOnInputPower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    }
   ]
  },
  {
   "title": "SD in MB",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Raspi",
     "query": "SELECT mean(\"Total\") FROM \"Raspi\" WHERE (\"instance\" = '/dev/root') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "/dev/mmcblk0p1" }
     ]
    },
    {
     "alias": "belegt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Raspi",
     "query": "SELECT mean(\"Total\") FROM \"Raspi\" WHERE (\"instance\" = '/dev/root') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "/dev/mmcblk0p1" }
     ]
    },
    {
     "alias": "frei",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Raspi",
     "query": "SELECT mean(\"Total\") FROM \"Raspi\" WHERE (\"instance\" = '/dev/root') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "/dev/mmcblk0p1" }
     ]
    }
   ]
  },
  {
   "title": "Batterie SoC und Temperatur",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 10, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "DcBatterySoc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "MultiPlus",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "Soc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "MultiPlus-II" }
     ]
    },
    {
     "alias": "BMV-700",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "Soc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "BMV-700" }
     ]
    },
    {
     "alias": "Temperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "Dc0Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "MultiPlus-II" }
     ]
    }
   ]
  }
 ]
}