{
 "title": "Mobile",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Stromfluss",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grid",
     "select": [
      [
       { "params": [ "AcPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "Dc0Current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "MultiPlus-II" }
     ]
    }
   ]
  },
  {
   "title": "Aktuelle Leistungen",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Netz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "grid",
     "select": [
      [
       { "params": [ "AcPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Meter" }
     ]
    },
    {
     "alias": "Ac Lasten",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "AcConsumptionOnInputPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "AcPvOnGridPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Batterie",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "DcBatteryPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Ertrag",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT max(\"PvInvertersAcEnergyForwardDay\") FROM \"system\" WHERE (\"instance\" = 'Gateway' AND \"PvInvertersAcEnergyForwardDay\" > 0 AND \"time\" > now()-1h) AND $timeFilter GROUP BY time(1d) fill(0)",
     "select": [
      [
       { "params": [ "PvInvertersAcEnergyForwardDay" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "now()-1h" }
     ]
    }
   ]
  },
  {
   "title": "Leistungen",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Sma",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "SMA" }
     ]
    },
    {
     "alias": "Piko",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "PIKO" }
     ]
    },
    {
     "alias": "Solar",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "AcPvOnGridPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Last",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "AcConsumptionOnInputPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Netz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grid",
     "select": [
      [
       { "params": [ "AcPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Meter" }
     ]
    },
    {
     "alias": "Batterie",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "DcBatteryPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "SoC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "DcBatterySoc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    }
   ]
  }
 ]
}