{
 "title": "Monat",
 "time": { "from": "now/M", "to": "now/M" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Tägliche Erzeugung",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       {
        "params": [
         "PvInvertersAcEnergyForwardDaySoFar"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Piko",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcEnergyForwardDaySoFar" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "PIKO" }
     ]
    },
    {
     "alias": "Sma",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcEnergyForwardDaySoFar" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "SMA" }
     ]
    }
   ]
  },
  {
   "title": "Tägliche Erzeugung",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       {
        "params": [
         "PvInvertersAcEnergyForwardDaySoFar"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Piko",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcEnergyForwardDaySoFar" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "PIKO" }
     ]
    },
    {
     "alias": "Sma",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcEnergyForwardDaySoFar" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "SMA" }
     ]
    }
   ]
  },
  {
   "title": "Tägliche Erzeugung",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       {
        "params": [
         "PvInvertersAcEnergyForwardDaySoFar"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Piko",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcEnergyForwardDaySoFar" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "PIKO" }
     ]
    },
    {
     "alias": "Sma",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcEnergyForwardDaySoFar" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "SMA" }
     ]
    },
    {
     "alias": "Heute",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "PvInvertersAcEnergyForwardDay" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" },
      { "condition": "AND", "key": "PvInvertersAcEnergyForwardDay", "operator": ">", "value": "0" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "now()-1h" }
     ]
    }
   ]
  },
  {
   "title": "Monatliche Erzeugung",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       {
        "params": [
         "PvInvertersAcEnergyForwardMonthSoFar"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Piko",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcEnergyForwardMonthSoFar" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "PIKO" }
     ]
    },
    {
     "alias": "Sma",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcEnergyForwardMonthSoFar" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "SMA" }
     ]
    }
   ]
  },
  {
   "title": "Monatliche Erzeugung",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       {
        "params": [
         "PvInvertersAcEnergyForwardMonthSoFar"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Piko",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcEnergyForwardMonthSoFar" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "PIKO" }
     ]
    },
    {
     "alias": "Sma",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcEnergyForwardMonthSoFar" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "SMA" }
     ]
    }
   ]
  },
  {
   "title": "Jährliche Erzeugung",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       {
        "params": [
         "PvInvertersAcEnergyForwardYearSoFar"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Piko",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcEnergyForwardYearSoFar" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "PIKO" }
     ]
    },
    {
     "alias": "Sma",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcEnergyForwardYearSoFar" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "SMA" }
     ]
    }
   ]
  },
  {
   "title": "Monatliche Erzeugung",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       {
        "params": [
         "PvInvertersAcEnergyForwardMonthSoFar"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Piko",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcEnergyForwardMonthSoFar" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "PIKO" }
     ]
    },
    {
     "alias": "Sma",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcEnergyForwardMonthSoFar" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "SMA" }
     ]
    }
   ]
  },
  {
   "title": "Netz Bezug/Lieferung letzter Monat",
   "type": "timeseries",
   "description": "positive Werte ist Bezug /Laden",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Solar",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "AcPvOnGridPower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Netz",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "grid",
     "select": [
      [
       { "params": [ "AcPower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Meter" }
     ]
    },
    {
     "alias": "Verbrauch",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "AcConsumptionOnInputPower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    }
   ]
  },
  {
   "title": "Batterieverlauf",
   "type": "timeseries",
   "description": "positive Werte sind Laden, negative Entladen",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Wh",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "DcBatteryPower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Ah",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "DcBatteryCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    }
   ]
  },
  {
   "title": "Batterieverlauf",
   "type": "timeseries",
   "description": "positive Werte sind Laden, negative Entladen",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Wh",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "DcBatteryPower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Ah",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "DcBatteryCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    }
   ]
  },
  {
   "title": "Tägliche Erzeugung",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Gesamt",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       {
        "params": [
         "PvInvertersAcEnergyForwardDaySoFar"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" }
     ]
    },
    {
     "alias": "Piko",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcEnergyForwardDaySoFar" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "PIKO" }
     ]
    },
    {
     "alias": "Sma",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcEnergyForwardDaySoFar" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "SMA" }
     ]
    },
    {
     "alias": "Heute",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "PvInvertersAcEnergyForwardDay" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "Gateway" },
      { "condition": "AND", "key": "PvInvertersAcEnergyForwardDay", "operator": ">", "value": "0" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "now()-1h" }
     ]
    }
   ]
  },
  {
   "title": "Batterie Zusammenfassung",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "Dc0Voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Spannung (V)" ], "type": "alias" }
      ],
      [
       { "params": [ "Dc0Current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Strom (A)" ], "type": "alias" }
      ],
      [
       { "params": [ "Dc0Power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Leistung (W)" ], "type": "alias" }
      ],
      [
       { "params": [ "ConsumedAmphours" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "verbrauchte Ah" ], "type": "alias" }
      ],
      [
       { "params": [ "Soc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "%" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "BMV-700" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vebus",
     "select": [
      [
       { "params": [ "Dc0Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "C" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "MultiPlus-II" }
     ]
    }
   ]
  },
  {
   "title": "SolarInverter Zusammenfassung",
   "type": "stat",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcL1Voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "SMA L1 V" ], "type": "alias" }
      ],
      [
       { "params": [ "AcL1Current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "SMA L1 A " ], "type": "alias" }
      ],
      [
       { "params": [ "AcL1Power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "SMA L1 W" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "SMA" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pvinverter",
     "select": [
      [
       { "params": [ "AcL1Voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "PIKO L1 V" ], "type": "alias" }
      ],
      [
       { "params": [ "AcL1Current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "PIKO L1 A" ], "type": "alias" }
      ],
      [
       { "params": [ "AcL1Power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "PIKO L1 W" ], "type": "alias" }
      ],
      [
       { "params": [ "AcL2Voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "PIKO L2 V" ], "type": "alias" }
      ],
      [
       { "params": [ "AcL2Current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "PIKO L2 A" ], "type": "alias" }
      ],
      [
       { "params": [ "AcL2Power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "PIKO L2 W" ], "type": "alias" }
      ],
      [
       { "params": [ "AcL3Voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "PIKO L3 V" ], "type": "alias" }
      ],
      [
       { "params": [ "AcL3Current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "PIKO L3  A" ], "type": "alias" }
      ],
      [
       { "params": [ "AcL3Power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "PIKO L3  W" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "PIKO" }
     ]
    }
   ]
  },
  {
   "title": "Batterie Historie",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "HistoryAutomaticSyncs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Anzahl SoC Synchronisationen" ], "type": "alias" }
      ],
      [
       { "params": [ "HistoryAverageDischarge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         "Durchschnittliche Entladung (Ah)"
        ],
        "type": "alias"
       }
      ],
      [
       { "params": [ "HistoryChargeCycles" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Ladezyklen" ], "type": "alias" }
      ],
      [
       { "params": [ "HistoryChargedEnergy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Eingeladene Energie (kWh)" ], "type": "alias" }
      ],
      [
       { "params": [ "HistoryDeepestDischarge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "tiefste Entladung (Ah)" ], "type": "alias" }
      ],
      [
       { "params": [ "HistoryDischargedEnergy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "entnommene Energie (kWh)" ], "type": "alias" }
      ],
      [
       { "params": [ "HistoryFullDischarges" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "komplett Entladen" ], "type": "alias" }
      ],
      [
       { "params": [ "HistoryLastDischarge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "letzte Entladung (Ah)" ], "type": "alias" }
      ],
      [
       { "params": [ "HistoryMaximumVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Max. Spannung (U)" ], "type": "alias" }
      ],
      [
       { "params": [ "HistoryMinimumVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Min. Spannung (U)" ], "type": "alias" }
      ],
      [
       { "params": [ "HistoryTimeSinceLastFullCharge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 3600" ], "type": "math" },
       {
        "params": [
         "Zeit seit dem letztem Vollladen (h)"
        ],
        "type": "alias"
       }
      ],
      [
       { "params": [ "HistoryTotalAhDrawn" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Gesamt entladene Ah" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "BMV-700" }
     ]
    }
   ]
  }
 ]
}